# Generated by Django 4.0 on 2022-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(blank=True, max_length=200, null=True)),
                ('custmobile', models.CharField(blank=True, max_length=200, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='fullname',
        ),
        migrations.AddField(
            model_name='medicine',
            name='qty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
