# Generated by Django 4.0 on 2022-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0002_cart_remove_pharmacist_fullname_medicine_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='invoicenumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
