# Generated by Django 4.0 on 2022-12-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0003_cart_invoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
