# Generated by Django 4.0 on 2022-12-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0004_cart_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='medicinename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicine'),
        ),
    ]
