# Generated by Django 4.0 on 2022-12-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0005_cart_medicinename'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Completed')], default=1, null=True),
        ),
    ]
