# Generated by Django 4.0.2 on 2022-12-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0006_cart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='creationdate',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='custmobile',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='custname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='invoicenumber',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='medicinename',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.pharmacist'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, max_length=100, null=True)),
                ('productid', models.TextField(blank=True, max_length=100, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Dispatch'), (2, 'Shipped'), (3, 'On the way'), (4, 'nearest to location'), (5, 'Delivered'), (6, 'Cancel'), (7, 'Return'), (8, 'Refund'), (9, 'Exchange')], default=1)),
                ('custmobile', models.CharField(blank=True, max_length=200, null=True)),
                ('custname', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.pharmacist')),
            ],
        ),
    ]
