# Generated by Django 4.0.2 on 2022-12-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0007_rename_creationdate_cart_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.pharmacist'),
        ),
    ]
