# Generated by Django 4.0.2 on 2022-12-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0008_medicine_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicine'),
        ),
    ]
