# Generated by Django 4.0.2 on 2022-12-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0010_remove_order_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacist',
        ),
    ]
