# Generated by Django 4.0.2 on 2022-12-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0014_alter_medicine_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='qty',
        ),
    ]
