# Generated by Django 4.0.2 on 2022-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0015_remove_medicine_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='qty',
            field=models.CharField(blank=True, default='20', max_length=200, null=True),
        ),
    ]
