# Generated by Django 4.0.2 on 2022-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0016_medicine_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='last',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
